---
title: "About Me"
author: Deniz Sevilmis
date: "`r Sys.Date()`"
output:
  pagedown::html_about:
    self_contained: true
---

Yasemin Deniz Sevilmis {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> deniz@sevilmis.net
- <i class="fa fa-envelope"></i> dsevilmis@utexas.edu
- <i class="fa fa-github"></i> [github.com/dsevilmis](https://github.com/dsevilmis)
- Feel free to contact me via email.


Skills
--------------------------------------------------------------------------------

- Can swim a 50m free in 26 seconds.

- Has a 10 step-skincare routine, please inquire.

- Proud winner of my 4th and 5th grade spelling bees, as well as State Finalist in Medical Spelling in 2017.


Education
--------------------------------------------------------------------------------

### University of Texas at Austin

B.S.A. in Biology | 2020  
Minor in Turkish
  
Austin, Texas

### Frisco High School

2017
Frisco, Texas

  

Employment & Academic Experiences (Brief)
--------------------------------------------------------------------------------
Please see resume on [Main](https://dsevilmis.netlify.app) page for a comprehensive resume.

### Swim Instructor
Gregory Gym, RecSports  
Austin, Texas  
2018

Frisco Athletic Center
Frisco, Texas
2015-2018
  
- Taught people how to not drown, rock their Iron Mans, swim competitively, and stay safe near and in the water
- Unsurprisingly, they are now all Olympians (Michael Phelps, anyone?)
- Just kidding, but they are all successful and can swim unassisted!

### Undergraduate Researcher/Peer Mentor/Teaching Assistant
Functional Genomics Lab
Department of Biomolecular Sciences at University of Texas at Austin
Austin, Texas  
2017-2019
  
- Independent porject studying the humanization of the yeast genome; particularly histone protein H4 in place of Hhf1 and Hhf2
- Ran lab meetings and educated freshman on how to conduct their own research as well as write and read scientific literature


Volunteer Work 
--------------------------------------------------------------------------------

### Posada Esperanza

General Volunteer, Homework Helper, Appointment Advocate
Austin, Texas  
2019-2020 

- Transitional housing program for refugee and immigrant mothers and children escaping political or domestic violence
- Helped with child care, homework, English practice, tutoring
- Took mothers and children to medical appointments, helped translate, direct to correct location with necessary materials/paperwork, advocate for patient if necessary

### Crisis Text Line

Crisis Counselor
(Virtual) 
2020 

- Free, 24/7 text line for people in crisis in the United States
- Support people through many troubles such as (but not limited to) : Anxiety, suicide, depression, bullying, self-harm, emotional abuse, loneliness, Coronavirus
- Trained in reflective listening, collaborative problem solving, safety planning and crisis management and intervention


